# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envolve < Formula
  desc "Synchronize environment variables across projects and manage .env files. Automates the restoration of .env files for all projects, ensures consistency by syncing variables from a global .env file, and creates symbolic links to maintain the latest environment settings."
  homepage "https://erdemkosk.github.io/envolve-app/"
  version "1.0.7"

  on_macos do
    on_intel do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.7/envolve_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1c9613ab9835108d799c36196703d4d587dc042ab33ed310f08d7fecbdf052dc"

      def install
        bin.install "envolve"
      end
    end
    on_arm do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.7/envolve_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "91f27f23babd2145f7e3b672de14497530adff1c168c497fea6c6d123814f54a"

      def install
        bin.install "envolve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.7/envolve_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "3a532239cf35a71c43d839711308f4683eaca194c308d21233c3b0754415741e"

        def install
          bin.install "envolve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.7/envolve_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "ddf189aeb63fe309d23d29b465867766197dea58109abe1c646596913229cd38"

        def install
          bin.install "envolve"
        end
      end
    end
  end
end
